/*
 * This source file was generated by the Gradle 'init' task
 */
package org.redbadger.app;

import java.util.HashSet;
import java.util.Scanner;
import java.util.Set;

public class RobotExecutor {

    public static void main(String[] args) {
        Scanner scan = new Scanner(System.in);
        String[] dimensions = scan.nextLine().split("\\s+");
        int maxX = Integer.parseInt(dimensions[0]);
        int maxY = Integer.parseInt(dimensions[1]);

        Set<String> scents = new HashSet<>();

        while(scan.hasNextLine()){
            String[] robotPosition = scan.nextLine().split("\\s+");
            int x = Integer.parseInt(robotPosition[0]);
            int y = Integer.parseInt(robotPosition[1]);
            ORIENTATION orientation = ORIENTATION.valueOf(robotPosition[2]);
            Robot robot = new Robot(x, y, orientation);
            String instructions = scan.nextLine().trim();
            System.out.println("Begining :: " + robot.getStatus());
            executeInstructions(robot, instructions, maxX, maxY, scents);
            System.out.println("Ending :: " + robot.getStatus());
        }
    }

    public static void executeInstructions(Robot robot, String instructions, int maxX, int maxY, Set<String> scents) {
        for(char instruction : instructions.toCharArray()){
            if(robot.isLost()){
                break;
            }
            switch (instruction) {
                case 'L': robot.turnLeft();break;
                case 'R': robot.turnRight();break;
                case 'F': robot.moveForward(maxX, maxY, scents);break;
                default: break;
            }
        }
    }
}
